version: '3.8'

services:
  bisikan-setan-bot:
    build: .
    container_name: bisikan-setan-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      # Optional: Mount logs directory if you want persistent logs
      - ./logs:/app/logs
    # Optional: Add health check
    healthcheck:
      test: ["CMD", "node", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
    # Optional: Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
